/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    assertIsInstructionForProgram,
    combineCodec,
    containsBytes,
    fixDecoderSize,
    fixEncoderSize,
    getAddressEncoder,
    getBytesDecoder,
    getBytesEncoder,
    getProgramDerivedAddress,
    getStructDecoder,
    getStructEncoder,
    SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
    SolanaError,
    transformEncoder,
    type AccountMeta,
    type AccountSignerMeta,
    type Address,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type Instruction,
    type InstructionWithAccounts,
    type InstructionWithData,
    type ReadonlyAccount,
    type ReadonlyUint8Array,
    type TransactionSigner,
    type WritableAccount,
    type WritableSignerAccount,
} from '@solana/kit';
import {
    getAccountMetaFactory,
    getAddressFromResolvedInstructionAccount,
    type ResolvedInstructionAccount,
} from '@solana/kit/program-client-core';
import { AUTHORITY_PDA_ADDRESS } from '../pdas/index.js';
import { RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS } from '../programs/index.js';

export const CLAIM_PLATFORM_FEE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
    156, 39, 208, 135, 76, 237, 61, 72,
]);

export function getClaimPlatformFeeDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(CLAIM_PLATFORM_FEE_DISCRIMINATOR);
}

export type ClaimPlatformFeeInstruction<
    TProgram extends string = typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
    TAccountPlatformFeeWallet extends string | AccountMeta<string> = string,
    TAccountAuthority extends string | AccountMeta<string> = 'WLHv2UAZm6z4KyaaELi5pjdbJh6RESMva1Rnn8pJVVh',
    TAccountPoolState extends string | AccountMeta<string> = string,
    TAccountPlatformConfig extends string | AccountMeta<string> = string,
    TAccountQuoteVault extends string | AccountMeta<string> = string,
    TAccountRecipientTokenAccount extends string | AccountMeta<string> = string,
    TAccountQuoteMint extends string | AccountMeta<string> = string,
    TAccountTokenProgram extends string | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    TAccountSystemProgram extends string | AccountMeta<string> = '11111111111111111111111111111111',
    TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
    TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
    InstructionWithData<ReadonlyUint8Array> &
    InstructionWithAccounts<
        [
            TAccountPlatformFeeWallet extends string
                ? WritableSignerAccount<TAccountPlatformFeeWallet> & AccountSignerMeta<TAccountPlatformFeeWallet>
                : TAccountPlatformFeeWallet,
            TAccountAuthority extends string ? ReadonlyAccount<TAccountAuthority> : TAccountAuthority,
            TAccountPoolState extends string ? WritableAccount<TAccountPoolState> : TAccountPoolState,
            TAccountPlatformConfig extends string ? ReadonlyAccount<TAccountPlatformConfig> : TAccountPlatformConfig,
            TAccountQuoteVault extends string ? WritableAccount<TAccountQuoteVault> : TAccountQuoteVault,
            TAccountRecipientTokenAccount extends string
                ? WritableAccount<TAccountRecipientTokenAccount>
                : TAccountRecipientTokenAccount,
            TAccountQuoteMint extends string ? ReadonlyAccount<TAccountQuoteMint> : TAccountQuoteMint,
            TAccountTokenProgram extends string ? ReadonlyAccount<TAccountTokenProgram> : TAccountTokenProgram,
            TAccountSystemProgram extends string ? ReadonlyAccount<TAccountSystemProgram> : TAccountSystemProgram,
            TAccountAssociatedTokenProgram extends string
                ? ReadonlyAccount<TAccountAssociatedTokenProgram>
                : TAccountAssociatedTokenProgram,
            ...TRemainingAccounts,
        ]
    >;

export type ClaimPlatformFeeInstructionData = { discriminator: ReadonlyUint8Array };

export type ClaimPlatformFeeInstructionDataArgs = {};

export function getClaimPlatformFeeInstructionDataEncoder(): FixedSizeEncoder<ClaimPlatformFeeInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]), value => ({
        ...value,
        discriminator: CLAIM_PLATFORM_FEE_DISCRIMINATOR,
    }));
}

export function getClaimPlatformFeeInstructionDataDecoder(): FixedSizeDecoder<ClaimPlatformFeeInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)]]);
}

export function getClaimPlatformFeeInstructionDataCodec(): FixedSizeCodec<
    ClaimPlatformFeeInstructionDataArgs,
    ClaimPlatformFeeInstructionData
> {
    return combineCodec(getClaimPlatformFeeInstructionDataEncoder(), getClaimPlatformFeeInstructionDataDecoder());
}

export type ClaimPlatformFeeAsyncInput<
    TAccountPlatformFeeWallet extends string = string,
    TAccountAuthority extends string = string,
    TAccountPoolState extends string = string,
    TAccountPlatformConfig extends string = string,
    TAccountQuoteVault extends string = string,
    TAccountRecipientTokenAccount extends string = string,
    TAccountQuoteMint extends string = string,
    TAccountTokenProgram extends string = string,
    TAccountSystemProgram extends string = string,
    TAccountAssociatedTokenProgram extends string = string,
> = {
    /** Only the wallet stored in platform_config can collect platform fees */
    platformFeeWallet: TransactionSigner<TAccountPlatformFeeWallet>;
    /**
     * PDA that acts as the authority for pool vault and mint operations
     * Generated using AUTH_SEED
     */
    authority?: Address<TAccountAuthority>;
    /**
     * Account that stores the pool's state and parameters
     * PDA generated using POOL_SEED and both token mints
     */
    poolState: Address<TAccountPoolState>;
    /** The platform config account */
    platformConfig: Address<TAccountPlatformConfig>;
    quoteVault: Address<TAccountQuoteVault>;
    /** The address that receives the collected quote token fees */
    recipientTokenAccount?: Address<TAccountRecipientTokenAccount>;
    /** The mint of quote token vault */
    quoteMint: Address<TAccountQuoteMint>;
    /** SPL program for input token transfers */
    tokenProgram?: Address<TAccountTokenProgram>;
    /** Required for account creation */
    systemProgram?: Address<TAccountSystemProgram>;
    /** Required for associated token program */
    associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
};

export async function getClaimPlatformFeeInstructionAsync<
    TAccountPlatformFeeWallet extends string,
    TAccountAuthority extends string,
    TAccountPoolState extends string,
    TAccountPlatformConfig extends string,
    TAccountQuoteVault extends string,
    TAccountRecipientTokenAccount extends string,
    TAccountQuoteMint extends string,
    TAccountTokenProgram extends string,
    TAccountSystemProgram extends string,
    TAccountAssociatedTokenProgram extends string,
>(
    input: ClaimPlatformFeeAsyncInput<
        TAccountPlatformFeeWallet,
        TAccountAuthority,
        TAccountPoolState,
        TAccountPlatformConfig,
        TAccountQuoteVault,
        TAccountRecipientTokenAccount,
        TAccountQuoteMint,
        TAccountTokenProgram,
        TAccountSystemProgram,
        TAccountAssociatedTokenProgram
    >,
): Promise<
    ClaimPlatformFeeInstruction<
        typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
        TAccountPlatformFeeWallet,
        TAccountAuthority,
        TAccountPoolState,
        TAccountPlatformConfig,
        TAccountQuoteVault,
        TAccountRecipientTokenAccount,
        TAccountQuoteMint,
        TAccountTokenProgram,
        TAccountSystemProgram,
        TAccountAssociatedTokenProgram
    >
> {
    // Program address.
    const programAddress = RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS;

    // Original accounts.
    const originalAccounts = {
        platformFeeWallet: { value: input.platformFeeWallet ?? null, isWritable: true },
        authority: { value: input.authority ?? null, isWritable: false },
        poolState: { value: input.poolState ?? null, isWritable: true },
        platformConfig: { value: input.platformConfig ?? null, isWritable: false },
        quoteVault: { value: input.quoteVault ?? null, isWritable: true },
        recipientTokenAccount: { value: input.recipientTokenAccount ?? null, isWritable: true },
        quoteMint: { value: input.quoteMint ?? null, isWritable: false },
        tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
        systemProgram: { value: input.systemProgram ?? null, isWritable: false },
        associatedTokenProgram: { value: input.associatedTokenProgram ?? null, isWritable: false },
    };
    const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;

    // Resolve default values.
    if (!accounts.authority.value) {
        accounts.authority.value = AUTHORITY_PDA_ADDRESS;
    }
    if (!accounts.recipientTokenAccount.value) {
        accounts.recipientTokenAccount.value = await getProgramDerivedAddress({
            programAddress:
                'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
            seeds: [
                getAddressEncoder().encode(
                    getAddressFromResolvedInstructionAccount('platformFeeWallet', accounts.platformFeeWallet.value),
                ),
                getBytesEncoder().encode(
                    new Uint8Array([
                        6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237,
                        95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169,
                    ]),
                ),
                getAddressEncoder().encode(
                    getAddressFromResolvedInstructionAccount('quoteMint', accounts.quoteMint.value),
                ),
            ],
        });
    }
    if (!accounts.tokenProgram.value) {
        accounts.tokenProgram.value =
            'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
    }
    if (!accounts.systemProgram.value) {
        accounts.systemProgram.value =
            '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
    }
    if (!accounts.associatedTokenProgram.value) {
        accounts.associatedTokenProgram.value =
            'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
    }

    const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
    return Object.freeze({
        accounts: [
            getAccountMeta('platformFeeWallet', accounts.platformFeeWallet),
            getAccountMeta('authority', accounts.authority),
            getAccountMeta('poolState', accounts.poolState),
            getAccountMeta('platformConfig', accounts.platformConfig),
            getAccountMeta('quoteVault', accounts.quoteVault),
            getAccountMeta('recipientTokenAccount', accounts.recipientTokenAccount),
            getAccountMeta('quoteMint', accounts.quoteMint),
            getAccountMeta('tokenProgram', accounts.tokenProgram),
            getAccountMeta('systemProgram', accounts.systemProgram),
            getAccountMeta('associatedTokenProgram', accounts.associatedTokenProgram),
        ],
        data: getClaimPlatformFeeInstructionDataEncoder().encode({}),
        programAddress,
    } as ClaimPlatformFeeInstruction<
        typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
        TAccountPlatformFeeWallet,
        TAccountAuthority,
        TAccountPoolState,
        TAccountPlatformConfig,
        TAccountQuoteVault,
        TAccountRecipientTokenAccount,
        TAccountQuoteMint,
        TAccountTokenProgram,
        TAccountSystemProgram,
        TAccountAssociatedTokenProgram
    >);
}

export type ClaimPlatformFeeInput<
    TAccountPlatformFeeWallet extends string = string,
    TAccountAuthority extends string = string,
    TAccountPoolState extends string = string,
    TAccountPlatformConfig extends string = string,
    TAccountQuoteVault extends string = string,
    TAccountRecipientTokenAccount extends string = string,
    TAccountQuoteMint extends string = string,
    TAccountTokenProgram extends string = string,
    TAccountSystemProgram extends string = string,
    TAccountAssociatedTokenProgram extends string = string,
> = {
    /** Only the wallet stored in platform_config can collect platform fees */
    platformFeeWallet: TransactionSigner<TAccountPlatformFeeWallet>;
    /**
     * PDA that acts as the authority for pool vault and mint operations
     * Generated using AUTH_SEED
     */
    authority?: Address<TAccountAuthority>;
    /**
     * Account that stores the pool's state and parameters
     * PDA generated using POOL_SEED and both token mints
     */
    poolState: Address<TAccountPoolState>;
    /** The platform config account */
    platformConfig: Address<TAccountPlatformConfig>;
    quoteVault: Address<TAccountQuoteVault>;
    /** The address that receives the collected quote token fees */
    recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
    /** The mint of quote token vault */
    quoteMint: Address<TAccountQuoteMint>;
    /** SPL program for input token transfers */
    tokenProgram?: Address<TAccountTokenProgram>;
    /** Required for account creation */
    systemProgram?: Address<TAccountSystemProgram>;
    /** Required for associated token program */
    associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
};

export function getClaimPlatformFeeInstruction<
    TAccountPlatformFeeWallet extends string,
    TAccountAuthority extends string,
    TAccountPoolState extends string,
    TAccountPlatformConfig extends string,
    TAccountQuoteVault extends string,
    TAccountRecipientTokenAccount extends string,
    TAccountQuoteMint extends string,
    TAccountTokenProgram extends string,
    TAccountSystemProgram extends string,
    TAccountAssociatedTokenProgram extends string,
>(
    input: ClaimPlatformFeeInput<
        TAccountPlatformFeeWallet,
        TAccountAuthority,
        TAccountPoolState,
        TAccountPlatformConfig,
        TAccountQuoteVault,
        TAccountRecipientTokenAccount,
        TAccountQuoteMint,
        TAccountTokenProgram,
        TAccountSystemProgram,
        TAccountAssociatedTokenProgram
    >,
): ClaimPlatformFeeInstruction<
    typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
    TAccountPlatformFeeWallet,
    TAccountAuthority,
    TAccountPoolState,
    TAccountPlatformConfig,
    TAccountQuoteVault,
    TAccountRecipientTokenAccount,
    TAccountQuoteMint,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram
> {
    // Program address.
    const programAddress = RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS;

    // Original accounts.
    const originalAccounts = {
        platformFeeWallet: { value: input.platformFeeWallet ?? null, isWritable: true },
        authority: { value: input.authority ?? null, isWritable: false },
        poolState: { value: input.poolState ?? null, isWritable: true },
        platformConfig: { value: input.platformConfig ?? null, isWritable: false },
        quoteVault: { value: input.quoteVault ?? null, isWritable: true },
        recipientTokenAccount: { value: input.recipientTokenAccount ?? null, isWritable: true },
        quoteMint: { value: input.quoteMint ?? null, isWritable: false },
        tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
        systemProgram: { value: input.systemProgram ?? null, isWritable: false },
        associatedTokenProgram: { value: input.associatedTokenProgram ?? null, isWritable: false },
    };
    const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;

    // Resolve default values.
    if (!accounts.authority.value) {
        accounts.authority.value = AUTHORITY_PDA_ADDRESS;
    }
    if (!accounts.tokenProgram.value) {
        accounts.tokenProgram.value =
            'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
    }
    if (!accounts.systemProgram.value) {
        accounts.systemProgram.value =
            '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
    }
    if (!accounts.associatedTokenProgram.value) {
        accounts.associatedTokenProgram.value =
            'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
    }

    const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
    return Object.freeze({
        accounts: [
            getAccountMeta('platformFeeWallet', accounts.platformFeeWallet),
            getAccountMeta('authority', accounts.authority),
            getAccountMeta('poolState', accounts.poolState),
            getAccountMeta('platformConfig', accounts.platformConfig),
            getAccountMeta('quoteVault', accounts.quoteVault),
            getAccountMeta('recipientTokenAccount', accounts.recipientTokenAccount),
            getAccountMeta('quoteMint', accounts.quoteMint),
            getAccountMeta('tokenProgram', accounts.tokenProgram),
            getAccountMeta('systemProgram', accounts.systemProgram),
            getAccountMeta('associatedTokenProgram', accounts.associatedTokenProgram),
        ],
        data: getClaimPlatformFeeInstructionDataEncoder().encode({}),
        programAddress,
    } as ClaimPlatformFeeInstruction<
        typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
        TAccountPlatformFeeWallet,
        TAccountAuthority,
        TAccountPoolState,
        TAccountPlatformConfig,
        TAccountQuoteVault,
        TAccountRecipientTokenAccount,
        TAccountQuoteMint,
        TAccountTokenProgram,
        TAccountSystemProgram,
        TAccountAssociatedTokenProgram
    >);
}

export type ParsedClaimPlatformFeeInstruction<
    TProgram extends string = typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
    TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
    programAddress: Address<TProgram>;
    accounts: {
        /** Only the wallet stored in platform_config can collect platform fees */
        platformFeeWallet: TAccountMetas[0];
        /**
         * PDA that acts as the authority for pool vault and mint operations
         * Generated using AUTH_SEED
         */
        authority: TAccountMetas[1];
        /**
         * Account that stores the pool's state and parameters
         * PDA generated using POOL_SEED and both token mints
         */
        poolState: TAccountMetas[2];
        /** The platform config account */
        platformConfig: TAccountMetas[3];
        quoteVault: TAccountMetas[4];
        /** The address that receives the collected quote token fees */
        recipientTokenAccount: TAccountMetas[5];
        /** The mint of quote token vault */
        quoteMint: TAccountMetas[6];
        /** SPL program for input token transfers */
        tokenProgram: TAccountMetas[7];
        /** Required for account creation */
        systemProgram: TAccountMetas[8];
        /** Required for associated token program */
        associatedTokenProgram: TAccountMetas[9];
    };
    data: ClaimPlatformFeeInstructionData;
};

export function parseClaimPlatformFeeInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(
    instruction: Instruction<TProgram> &
        InstructionWithAccounts<TAccountMetas> &
        InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimPlatformFeeInstruction<TProgram, TAccountMetas> {
    assertIsInstructionForProgram(instruction, RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS);
    if (!containsBytes(instruction.data, CLAIM_PLATFORM_FEE_DISCRIMINATOR, 0)) {
        const error = new Error(
            `parseClaimPlatformFeeInstruction: instruction data does not match the ClaimPlatformFee discriminator`,
        );
        error.name = 'InstructionDiscriminatorMismatchError';
        throw error;
    }
    if (instruction.accounts.length < 10) {
        throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
            actualAccountMetas: instruction.accounts.length,
            expectedAccountMetas: 10,
        });
    }
    let accountIndex = 0;
    const getNextAccount = () => {
        const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
        accountIndex += 1;
        return accountMeta;
    };
    return {
        programAddress: instruction.programAddress,
        accounts: {
            platformFeeWallet: getNextAccount(),
            authority: getNextAccount(),
            poolState: getNextAccount(),
            platformConfig: getNextAccount(),
            quoteVault: getNextAccount(),
            recipientTokenAccount: getNextAccount(),
            quoteMint: getNextAccount(),
            tokenProgram: getNextAccount(),
            systemProgram: getNextAccount(),
            associatedTokenProgram: getNextAccount(),
        },
        data: getClaimPlatformFeeInstructionDataDecoder().decode(instruction.data),
    };
}
