/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    assertIsInstructionForProgram,
    combineCodec,
    containsBytes,
    fixDecoderSize,
    fixEncoderSize,
    getBytesDecoder,
    getBytesEncoder,
    getStructDecoder,
    getStructEncoder,
    SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
    SolanaError,
    transformEncoder,
    type AccountMeta,
    type AccountSignerMeta,
    type Address,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type Instruction,
    type InstructionWithAccounts,
    type InstructionWithData,
    type ReadonlyAccount,
    type ReadonlySignerAccount,
    type ReadonlyUint8Array,
    type TransactionSigner,
    type WritableAccount,
} from '@solana/kit';
import { getAccountMetaFactory, type ResolvedInstructionAccount } from '@solana/kit/program-client-core';
import { AUTHORITY_PDA_ADDRESS } from '../pdas/index.js';
import { RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS } from '../programs/index.js';

export const COLLECT_FEE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([60, 173, 247, 103, 4, 93, 130, 48]);

export function getCollectFeeDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(COLLECT_FEE_DISCRIMINATOR);
}

export type CollectFeeInstruction<
    TProgram extends string = typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
    TAccountOwner extends string | AccountMeta<string> = string,
    TAccountAuthority extends string | AccountMeta<string> = 'WLHv2UAZm6z4KyaaELi5pjdbJh6RESMva1Rnn8pJVVh',
    TAccountPoolState extends string | AccountMeta<string> = string,
    TAccountGlobalConfig extends string | AccountMeta<string> = string,
    TAccountQuoteVault extends string | AccountMeta<string> = string,
    TAccountQuoteMint extends string | AccountMeta<string> = string,
    TAccountRecipientTokenAccount extends string | AccountMeta<string> = string,
    TAccountTokenProgram extends string | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
    InstructionWithData<ReadonlyUint8Array> &
    InstructionWithAccounts<
        [
            TAccountOwner extends string
                ? ReadonlySignerAccount<TAccountOwner> & AccountSignerMeta<TAccountOwner>
                : TAccountOwner,
            TAccountAuthority extends string ? ReadonlyAccount<TAccountAuthority> : TAccountAuthority,
            TAccountPoolState extends string ? WritableAccount<TAccountPoolState> : TAccountPoolState,
            TAccountGlobalConfig extends string ? ReadonlyAccount<TAccountGlobalConfig> : TAccountGlobalConfig,
            TAccountQuoteVault extends string ? WritableAccount<TAccountQuoteVault> : TAccountQuoteVault,
            TAccountQuoteMint extends string ? ReadonlyAccount<TAccountQuoteMint> : TAccountQuoteMint,
            TAccountRecipientTokenAccount extends string
                ? WritableAccount<TAccountRecipientTokenAccount>
                : TAccountRecipientTokenAccount,
            TAccountTokenProgram extends string ? ReadonlyAccount<TAccountTokenProgram> : TAccountTokenProgram,
            ...TRemainingAccounts,
        ]
    >;

export type CollectFeeInstructionData = { discriminator: ReadonlyUint8Array };

export type CollectFeeInstructionDataArgs = {};

export function getCollectFeeInstructionDataEncoder(): FixedSizeEncoder<CollectFeeInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]), value => ({
        ...value,
        discriminator: COLLECT_FEE_DISCRIMINATOR,
    }));
}

export function getCollectFeeInstructionDataDecoder(): FixedSizeDecoder<CollectFeeInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)]]);
}

export function getCollectFeeInstructionDataCodec(): FixedSizeCodec<
    CollectFeeInstructionDataArgs,
    CollectFeeInstructionData
> {
    return combineCodec(getCollectFeeInstructionDataEncoder(), getCollectFeeInstructionDataDecoder());
}

export type CollectFeeInput<
    TAccountOwner extends string = string,
    TAccountPoolState extends string = string,
    TAccountGlobalConfig extends string = string,
    TAccountQuoteVault extends string = string,
    TAccountQuoteMint extends string = string,
    TAccountRecipientTokenAccount extends string = string,
> = {
    /** Only protocol_fee_owner saved in global_config can collect protocol fee now */
    owner: TransactionSigner<TAccountOwner>;
    /** Pool state stores accumulated protocol fee amount */
    poolState: Address<TAccountPoolState>;
    /** Global config account stores owner */
    globalConfig: Address<TAccountGlobalConfig>;
    /** The address that holds pool tokens for quote token */
    quoteVault: Address<TAccountQuoteVault>;
    /** The mint of quote token vault */
    quoteMint: Address<TAccountQuoteMint>;
    /** The address that receives the collected quote token fees */
    recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
};

export function getCollectFeeInstruction<
    TAccountOwner extends string,
    TAccountPoolState extends string,
    TAccountGlobalConfig extends string,
    TAccountQuoteVault extends string,
    TAccountQuoteMint extends string,
    TAccountRecipientTokenAccount extends string,
>(
    input: CollectFeeInput<
        TAccountOwner,
        TAccountPoolState,
        TAccountGlobalConfig,
        TAccountQuoteVault,
        TAccountQuoteMint,
        TAccountRecipientTokenAccount
    >,
): CollectFeeInstruction<
    typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
    TAccountOwner,
    'WLHv2UAZm6z4KyaaELi5pjdbJh6RESMva1Rnn8pJVVh',
    TAccountPoolState,
    TAccountGlobalConfig,
    TAccountQuoteVault,
    TAccountQuoteMint,
    TAccountRecipientTokenAccount,
    'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
> {
    // Program address.
    const programAddress = RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS;

    // Original accounts.
    const originalAccounts = {
        owner: { value: input.owner ?? null, isWritable: false },
        authority: { value: null, isWritable: false },
        poolState: { value: input.poolState ?? null, isWritable: true },
        globalConfig: { value: input.globalConfig ?? null, isWritable: false },
        quoteVault: { value: input.quoteVault ?? null, isWritable: true },
        quoteMint: { value: input.quoteMint ?? null, isWritable: false },
        recipientTokenAccount: { value: input.recipientTokenAccount ?? null, isWritable: true },
        tokenProgram: { value: null, isWritable: false },
    };
    const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;

    // Resolve default values.
    if (!accounts.authority.value) {
        accounts.authority.value = AUTHORITY_PDA_ADDRESS;
    }
    if (!accounts.tokenProgram.value) {
        accounts.tokenProgram.value =
            'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
    }

    const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
    return Object.freeze({
        accounts: [
            getAccountMeta('owner', accounts.owner),
            getAccountMeta('authority', accounts.authority),
            getAccountMeta('poolState', accounts.poolState),
            getAccountMeta('globalConfig', accounts.globalConfig),
            getAccountMeta('quoteVault', accounts.quoteVault),
            getAccountMeta('quoteMint', accounts.quoteMint),
            getAccountMeta('recipientTokenAccount', accounts.recipientTokenAccount),
            getAccountMeta('tokenProgram', accounts.tokenProgram),
        ],
        data: getCollectFeeInstructionDataEncoder().encode({}),
        programAddress,
    } as CollectFeeInstruction<
        typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
        TAccountOwner,
        'WLHv2UAZm6z4KyaaELi5pjdbJh6RESMva1Rnn8pJVVh',
        TAccountPoolState,
        TAccountGlobalConfig,
        TAccountQuoteVault,
        TAccountQuoteMint,
        TAccountRecipientTokenAccount,
        'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    >);
}

export type ParsedCollectFeeInstruction<
    TProgram extends string = typeof RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
    TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
    programAddress: Address<TProgram>;
    accounts: {
        /** Only protocol_fee_owner saved in global_config can collect protocol fee now */
        owner: TAccountMetas[0];
        authority: TAccountMetas[1];
        /** Pool state stores accumulated protocol fee amount */
        poolState: TAccountMetas[2];
        /** Global config account stores owner */
        globalConfig: TAccountMetas[3];
        /** The address that holds pool tokens for quote token */
        quoteVault: TAccountMetas[4];
        /** The mint of quote token vault */
        quoteMint: TAccountMetas[5];
        /** The address that receives the collected quote token fees */
        recipientTokenAccount: TAccountMetas[6];
        /** SPL program for input token transfers */
        tokenProgram: TAccountMetas[7];
    };
    data: CollectFeeInstructionData;
};

export function parseCollectFeeInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(
    instruction: Instruction<TProgram> &
        InstructionWithAccounts<TAccountMetas> &
        InstructionWithData<ReadonlyUint8Array>,
): ParsedCollectFeeInstruction<TProgram, TAccountMetas> {
    assertIsInstructionForProgram(instruction, RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS);
    if (!containsBytes(instruction.data, COLLECT_FEE_DISCRIMINATOR, 0)) {
        const error = new Error(
            `parseCollectFeeInstruction: instruction data does not match the CollectFee discriminator`,
        );
        error.name = 'InstructionDiscriminatorMismatchError';
        throw error;
    }
    if (instruction.accounts.length < 8) {
        throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, {
            actualAccountMetas: instruction.accounts.length,
            expectedAccountMetas: 8,
        });
    }
    let accountIndex = 0;
    const getNextAccount = () => {
        const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
        accountIndex += 1;
        return accountMeta;
    };
    return {
        programAddress: instruction.programAddress,
        accounts: {
            owner: getNextAccount(),
            authority: getNextAccount(),
            poolState: getNextAccount(),
            globalConfig: getNextAccount(),
            quoteVault: getNextAccount(),
            quoteMint: getNextAccount(),
            recipientTokenAccount: getNextAccount(),
            tokenProgram: getNextAccount(),
        },
        data: getCollectFeeInstructionDataDecoder().decode(instruction.data),
    };
}
