/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    assertIsInstructionWithAccounts,
    containsBytes,
    type Instruction,
    type InstructionWithData,
    type ReadonlyUint8Array,
} from '@solana/kit';
import {
    BUY_EXACT_IN_DISCRIMINATOR,
    parseBuyExactInInstruction,
    type ParsedBuyExactInInstruction,
} from './buyExactIn.js';
import {
    BUY_EXACT_OUT_DISCRIMINATOR,
    parseBuyExactOutInstruction,
    type ParsedBuyExactOutInstruction,
} from './buyExactOut.js';
import {
    CLAIM_PLATFORM_FEE_DISCRIMINATOR,
    parseClaimPlatformFeeInstruction,
    type ParsedClaimPlatformFeeInstruction,
} from './claimPlatformFee.js';
import {
    CLAIM_VESTED_TOKEN_DISCRIMINATOR,
    parseClaimVestedTokenInstruction,
    type ParsedClaimVestedTokenInstruction,
} from './claimVestedToken.js';
import {
    COLLECT_FEE_DISCRIMINATOR,
    parseCollectFeeInstruction,
    type ParsedCollectFeeInstruction,
} from './collectFee.js';
import {
    COLLECT_MIGRATE_FEE_DISCRIMINATOR,
    parseCollectMigrateFeeInstruction,
    type ParsedCollectMigrateFeeInstruction,
} from './collectMigrateFee.js';
import {
    CREATE_CONFIG_DISCRIMINATOR,
    parseCreateConfigInstruction,
    type ParsedCreateConfigInstruction,
} from './createConfig.js';
import {
    CREATE_PLATFORM_CONFIG_DISCRIMINATOR,
    parseCreatePlatformConfigInstruction,
    type ParsedCreatePlatformConfigInstruction,
} from './createPlatformConfig.js';
import {
    CREATE_VESTING_ACCOUNT_DISCRIMINATOR,
    parseCreateVestingAccountInstruction,
    type ParsedCreateVestingAccountInstruction,
} from './createVestingAccount.js';
import {
    INITIALIZE_DISCRIMINATOR,
    parseInitializeInstruction,
    type ParsedInitializeInstruction,
} from './initialize.js';
import {
    MIGRATE_TO_AMM_DISCRIMINATOR,
    parseMigrateToAmmInstruction,
    type ParsedMigrateToAmmInstruction,
} from './migrateToAmm.js';
import {
    MIGRATE_TO_CPSWAP_DISCRIMINATOR,
    parseMigrateToCpswapInstruction,
    type ParsedMigrateToCpswapInstruction,
} from './migrateToCpswap.js';
import {
    parseSellExactInInstruction,
    SELL_EXACT_IN_DISCRIMINATOR,
    type ParsedSellExactInInstruction,
} from './sellExactIn.js';
import {
    parseSellExactOutInstruction,
    SELL_EXACT_OUT_DISCRIMINATOR,
    type ParsedSellExactOutInstruction,
} from './sellExactOut.js';
import {
    parseUpdateConfigInstruction,
    type ParsedUpdateConfigInstruction,
    UPDATE_CONFIG_DISCRIMINATOR,
} from './updateConfig.js';
import {
    parseUpdatePlatformConfigInstruction,
    type ParsedUpdatePlatformConfigInstruction,
    UPDATE_PLATFORM_CONFIG_DISCRIMINATOR,
} from './updatePlatformConfig.js';

/** Instruction kinds of the raydiumLaunchpad program. */
export type InstructionType =
    | 'buyExactIn'
    | 'buyExactOut'
    | 'claimPlatformFee'
    | 'claimVestedToken'
    | 'collectFee'
    | 'collectMigrateFee'
    | 'createConfig'
    | 'createPlatformConfig'
    | 'createVestingAccount'
    | 'initialize'
    | 'migrateToAmm'
    | 'migrateToCpswap'
    | 'sellExactIn'
    | 'sellExactOut'
    | 'updateConfig'
    | 'updatePlatformConfig';

/**
 * Identifies raydiumLaunchpad instruction data by its discriminators.
 * Returns `null` when the data matches no known instruction.
 */
export function identifyInstruction(
    instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): InstructionType | null {
    const data = 'data' in instruction ? instruction.data : instruction;
    if (containsBytes(data, BUY_EXACT_IN_DISCRIMINATOR, 0)) {
        return 'buyExactIn';
    }
    if (containsBytes(data, BUY_EXACT_OUT_DISCRIMINATOR, 0)) {
        return 'buyExactOut';
    }
    if (containsBytes(data, CLAIM_PLATFORM_FEE_DISCRIMINATOR, 0)) {
        return 'claimPlatformFee';
    }
    if (containsBytes(data, CLAIM_VESTED_TOKEN_DISCRIMINATOR, 0)) {
        return 'claimVestedToken';
    }
    if (containsBytes(data, COLLECT_FEE_DISCRIMINATOR, 0)) {
        return 'collectFee';
    }
    if (containsBytes(data, COLLECT_MIGRATE_FEE_DISCRIMINATOR, 0)) {
        return 'collectMigrateFee';
    }
    if (containsBytes(data, CREATE_CONFIG_DISCRIMINATOR, 0)) {
        return 'createConfig';
    }
    if (containsBytes(data, CREATE_PLATFORM_CONFIG_DISCRIMINATOR, 0)) {
        return 'createPlatformConfig';
    }
    if (containsBytes(data, CREATE_VESTING_ACCOUNT_DISCRIMINATOR, 0)) {
        return 'createVestingAccount';
    }
    if (containsBytes(data, INITIALIZE_DISCRIMINATOR, 0)) {
        return 'initialize';
    }
    if (containsBytes(data, MIGRATE_TO_AMM_DISCRIMINATOR, 0)) {
        return 'migrateToAmm';
    }
    if (containsBytes(data, MIGRATE_TO_CPSWAP_DISCRIMINATOR, 0)) {
        return 'migrateToCpswap';
    }
    if (containsBytes(data, SELL_EXACT_IN_DISCRIMINATOR, 0)) {
        return 'sellExactIn';
    }
    if (containsBytes(data, SELL_EXACT_OUT_DISCRIMINATOR, 0)) {
        return 'sellExactOut';
    }
    if (containsBytes(data, UPDATE_CONFIG_DISCRIMINATOR, 0)) {
        return 'updateConfig';
    }
    if (containsBytes(data, UPDATE_PLATFORM_CONFIG_DISCRIMINATOR, 0)) {
        return 'updatePlatformConfig';
    }
    return null;
}

/** Parsed raydiumLaunchpad instruction: the instruction kind tag plus its parsed accounts and data. */
export type ParsedInstruction<TProgram extends string = 'LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj'> =
    | ({ kind: 'buyExactIn' } & ParsedBuyExactInInstruction<TProgram>)
    | ({ kind: 'buyExactOut' } & ParsedBuyExactOutInstruction<TProgram>)
    | ({ kind: 'claimPlatformFee' } & ParsedClaimPlatformFeeInstruction<TProgram>)
    | ({ kind: 'claimVestedToken' } & ParsedClaimVestedTokenInstruction<TProgram>)
    | ({ kind: 'collectFee' } & ParsedCollectFeeInstruction<TProgram>)
    | ({ kind: 'collectMigrateFee' } & ParsedCollectMigrateFeeInstruction<TProgram>)
    | ({ kind: 'createConfig' } & ParsedCreateConfigInstruction<TProgram>)
    | ({ kind: 'createPlatformConfig' } & ParsedCreatePlatformConfigInstruction<TProgram>)
    | ({ kind: 'createVestingAccount' } & ParsedCreateVestingAccountInstruction<TProgram>)
    | ({ kind: 'initialize' } & ParsedInitializeInstruction<TProgram>)
    | ({ kind: 'migrateToAmm' } & ParsedMigrateToAmmInstruction<TProgram>)
    | ({ kind: 'migrateToCpswap' } & ParsedMigrateToCpswapInstruction<TProgram>)
    | ({ kind: 'sellExactIn' } & ParsedSellExactInInstruction<TProgram>)
    | ({ kind: 'sellExactOut' } & ParsedSellExactOutInstruction<TProgram>)
    | ({ kind: 'updateConfig' } & ParsedUpdateConfigInstruction<TProgram>)
    | ({ kind: 'updatePlatformConfig' } & ParsedUpdatePlatformConfigInstruction<TProgram>);

/**
 * Parses a raydiumLaunchpad instruction into its kind tag plus parsed accounts and data.
 * Returns `null` when no known instruction matches; throws if a matched instruction fails to parse.
 */
export function parseInstruction<TProgram extends string>(
    instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedInstruction<TProgram> | null {
    const instructionType = identifyInstruction(instruction);
    if (instructionType === null) return null;
    switch (instructionType) {
        case 'buyExactIn': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'buyExactIn', ...parseBuyExactInInstruction(instruction) };
        }
        case 'buyExactOut': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'buyExactOut', ...parseBuyExactOutInstruction(instruction) };
        }
        case 'claimPlatformFee': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'claimPlatformFee', ...parseClaimPlatformFeeInstruction(instruction) };
        }
        case 'claimVestedToken': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'claimVestedToken', ...parseClaimVestedTokenInstruction(instruction) };
        }
        case 'collectFee': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'collectFee', ...parseCollectFeeInstruction(instruction) };
        }
        case 'collectMigrateFee': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'collectMigrateFee', ...parseCollectMigrateFeeInstruction(instruction) };
        }
        case 'createConfig': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'createConfig', ...parseCreateConfigInstruction(instruction) };
        }
        case 'createPlatformConfig': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'createPlatformConfig', ...parseCreatePlatformConfigInstruction(instruction) };
        }
        case 'createVestingAccount': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'createVestingAccount', ...parseCreateVestingAccountInstruction(instruction) };
        }
        case 'initialize': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'initialize', ...parseInitializeInstruction(instruction) };
        }
        case 'migrateToAmm': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'migrateToAmm', ...parseMigrateToAmmInstruction(instruction) };
        }
        case 'migrateToCpswap': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'migrateToCpswap', ...parseMigrateToCpswapInstruction(instruction) };
        }
        case 'sellExactIn': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'sellExactIn', ...parseSellExactInInstruction(instruction) };
        }
        case 'sellExactOut': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'sellExactOut', ...parseSellExactOutInstruction(instruction) };
        }
        case 'updateConfig': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'updateConfig', ...parseUpdateConfigInstruction(instruction) };
        }
        case 'updatePlatformConfig': {
            assertIsInstructionWithAccounts(instruction);
            return { kind: 'updatePlatformConfig', ...parseUpdatePlatformConfigInstruction(instruction) };
        }
    }
}
