/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    extendClient,
    type ClientWithPayer,
    type ClientWithRpc,
    type ClientWithTransactionPlanning,
    type ClientWithTransactionSending,
    type GetAccountInfoApi,
    type GetMultipleAccountsApi,
} from '@solana/kit';
import {
    addSelfPlanAndSendFunctions,
    type SelfFetchFunctions,
    type SelfPlanAndSendFunctions,
} from '@solana/kit/program-client-core';
import {
    fetchAllGlobalConfig,
    fetchAllMaybeGlobalConfig,
    fetchAllMaybePlatformConfig,
    fetchAllMaybePoolState,
    fetchAllMaybeVestingRecord,
    fetchAllPlatformConfig,
    fetchAllPoolState,
    fetchAllVestingRecord,
    fetchGlobalConfig,
    fetchMaybeGlobalConfig,
    fetchMaybePlatformConfig,
    fetchMaybePoolState,
    fetchMaybeVestingRecord,
    fetchPlatformConfig,
    fetchPoolState,
    fetchVestingRecord,
    getGlobalConfigCodec,
    getPlatformConfigCodec,
    getPoolStateCodec,
    getVestingRecordCodec,
    identifyAccount,
    type GlobalConfig,
    type GlobalConfigArgs,
    type PlatformConfig,
    type PlatformConfigArgs,
    type PoolState,
    type PoolStateArgs,
    type VestingRecord,
    type VestingRecordArgs,
} from '../accounts/index.js';
import {
    getClaimVestedEventDecoder,
    getCreateVestingEventDecoder,
    getPoolCreateEventDecoder,
    getTradeEventDecoder,
} from '../events/index.js';
import {
    getBuyExactInInstructionAsync,
    getBuyExactOutInstructionAsync,
    getClaimPlatformFeeInstructionAsync,
    getClaimVestedTokenInstructionAsync,
    getCollectFeeInstructionAsync,
    getCollectMigrateFeeInstructionAsync,
    getCreateConfigInstructionAsync,
    getCreatePlatformConfigInstructionAsync,
    getCreateVestingAccountInstructionAsync,
    getInitializeInstructionAsync,
    getMigrateToAmmInstructionAsync,
    getMigrateToCpswapInstructionAsync,
    getSellExactInInstructionAsync,
    getSellExactOutInstructionAsync,
    getUpdateConfigInstruction,
    getUpdatePlatformConfigInstructionAsync,
    identifyInstruction,
    parseInstruction,
    type BuyExactInAsyncInput,
    type BuyExactOutAsyncInput,
    type ClaimPlatformFeeAsyncInput,
    type ClaimVestedTokenAsyncInput,
    type CollectFeeAsyncInput,
    type CollectMigrateFeeAsyncInput,
    type CreateConfigAsyncInput,
    type CreatePlatformConfigAsyncInput,
    type CreateVestingAccountAsyncInput,
    type InitializeAsyncInput,
    type MigrateToAmmAsyncInput,
    type MigrateToCpswapAsyncInput,
    type SellExactInAsyncInput,
    type SellExactOutAsyncInput,
    type UpdateConfigInput,
    type UpdatePlatformConfigAsyncInput,
} from '../instructions/index.js';
import {
    findAmmAuthorityPda,
    findAmmBaseVaultPda,
    findAmmConfigPda,
    findAmmLpMintPda,
    findAmmOpenOrdersPda,
    findAmmPoolPda,
    findAmmQuoteVaultPda,
    findAmmTargetOrdersPda,
    findAuthorityPda,
    findBaseVaultPda,
    findCpswapAuthorityPda,
    findCpswapBaseVaultPda,
    findCpswapLpMintPda,
    findCpswapObservationPda,
    findCpswapQuoteVaultPda,
    findEventAuthorityPda,
    findGlobalConfigPda,
    findLockAuthorityPda,
    findPlatformConfigPda,
    findPoolStatePda,
    findQuoteVaultPda,
    findVestingRecordPda,
} from '../pdas/index.js';

export type RaydiumLaunchpadPlugin = {
    accounts: RaydiumLaunchpadPluginAccounts;
    events: RaydiumLaunchpadPluginEvents;
    instructions: RaydiumLaunchpadPluginInstructions;
    pdas: RaydiumLaunchpadPluginPdas;
    identifyAccount: typeof identifyAccount;
    identifyInstruction: typeof identifyInstruction;
    parseInstruction: typeof parseInstruction;
};

export type RaydiumLaunchpadPluginAccounts = {
    globalConfig: ReturnType<typeof getGlobalConfigCodec> & SelfFetchFunctions<GlobalConfigArgs, GlobalConfig>;
    platformConfig: ReturnType<typeof getPlatformConfigCodec> & SelfFetchFunctions<PlatformConfigArgs, PlatformConfig>;
    poolState: ReturnType<typeof getPoolStateCodec> & SelfFetchFunctions<PoolStateArgs, PoolState>;
    vestingRecord: ReturnType<typeof getVestingRecordCodec> & SelfFetchFunctions<VestingRecordArgs, VestingRecord>;
};

export type RaydiumLaunchpadPluginEvents = {
    claimVestedEvent: ReturnType<typeof getClaimVestedEventDecoder>;
    createVestingEvent: ReturnType<typeof getCreateVestingEventDecoder>;
    poolCreateEvent: ReturnType<typeof getPoolCreateEventDecoder>;
    tradeEvent: ReturnType<typeof getTradeEventDecoder>;
};

export type RaydiumLaunchpadPluginInstructions = {
    buyExactIn: (
        input: MakeOptional<BuyExactInAsyncInput, 'payer'>,
    ) => ReturnType<typeof getBuyExactInInstructionAsync> & SelfPlanAndSendFunctions;
    buyExactOut: (
        input: MakeOptional<BuyExactOutAsyncInput, 'payer'>,
    ) => ReturnType<typeof getBuyExactOutInstructionAsync> & SelfPlanAndSendFunctions;
    claimPlatformFee: (
        input: ClaimPlatformFeeAsyncInput,
    ) => ReturnType<typeof getClaimPlatformFeeInstructionAsync> & SelfPlanAndSendFunctions;
    claimVestedToken: (
        input: ClaimVestedTokenAsyncInput,
    ) => ReturnType<typeof getClaimVestedTokenInstructionAsync> & SelfPlanAndSendFunctions;
    collectFee: (
        input: CollectFeeAsyncInput,
    ) => ReturnType<typeof getCollectFeeInstructionAsync> & SelfPlanAndSendFunctions;
    collectMigrateFee: (
        input: CollectMigrateFeeAsyncInput,
    ) => ReturnType<typeof getCollectMigrateFeeInstructionAsync> & SelfPlanAndSendFunctions;
    createConfig: (
        input: CreateConfigAsyncInput,
    ) => ReturnType<typeof getCreateConfigInstructionAsync> & SelfPlanAndSendFunctions;
    createPlatformConfig: (
        input: CreatePlatformConfigAsyncInput,
    ) => ReturnType<typeof getCreatePlatformConfigInstructionAsync> & SelfPlanAndSendFunctions;
    createVestingAccount: (
        input: CreateVestingAccountAsyncInput,
    ) => ReturnType<typeof getCreateVestingAccountInstructionAsync> & SelfPlanAndSendFunctions;
    initialize: (
        input: MakeOptional<InitializeAsyncInput, 'payer'>,
    ) => ReturnType<typeof getInitializeInstructionAsync> & SelfPlanAndSendFunctions;
    migrateToAmm: (
        input: MakeOptional<MigrateToAmmAsyncInput, 'payer'>,
    ) => ReturnType<typeof getMigrateToAmmInstructionAsync> & SelfPlanAndSendFunctions;
    migrateToCpswap: (
        input: MakeOptional<MigrateToCpswapAsyncInput, 'payer'>,
    ) => ReturnType<typeof getMigrateToCpswapInstructionAsync> & SelfPlanAndSendFunctions;
    sellExactIn: (
        input: MakeOptional<SellExactInAsyncInput, 'payer'>,
    ) => ReturnType<typeof getSellExactInInstructionAsync> & SelfPlanAndSendFunctions;
    sellExactOut: (
        input: MakeOptional<SellExactOutAsyncInput, 'payer'>,
    ) => ReturnType<typeof getSellExactOutInstructionAsync> & SelfPlanAndSendFunctions;
    updateConfig: (
        input: UpdateConfigInput,
    ) => ReturnType<typeof getUpdateConfigInstruction> & SelfPlanAndSendFunctions;
    updatePlatformConfig: (
        input: UpdatePlatformConfigAsyncInput,
    ) => ReturnType<typeof getUpdatePlatformConfigInstructionAsync> & SelfPlanAndSendFunctions;
};

export type RaydiumLaunchpadPluginPdas = {
    authority: typeof findAuthorityPda;
    eventAuthority: typeof findEventAuthorityPda;
    vestingRecord: typeof findVestingRecordPda;
    globalConfig: typeof findGlobalConfigPda;
    platformConfig: typeof findPlatformConfigPda;
    poolState: typeof findPoolStatePda;
    baseVault: typeof findBaseVaultPda;
    quoteVault: typeof findQuoteVaultPda;
    ammPool: typeof findAmmPoolPda;
    ammAuthority: typeof findAmmAuthorityPda;
    ammOpenOrders: typeof findAmmOpenOrdersPda;
    ammLpMint: typeof findAmmLpMintPda;
    ammBaseVault: typeof findAmmBaseVaultPda;
    ammQuoteVault: typeof findAmmQuoteVaultPda;
    ammTargetOrders: typeof findAmmTargetOrdersPda;
    ammConfig: typeof findAmmConfigPda;
    cpswapAuthority: typeof findCpswapAuthorityPda;
    cpswapLpMint: typeof findCpswapLpMintPda;
    cpswapBaseVault: typeof findCpswapBaseVaultPda;
    cpswapQuoteVault: typeof findCpswapQuoteVaultPda;
    cpswapObservation: typeof findCpswapObservationPda;
    lockAuthority: typeof findLockAuthorityPda;
};

export type RaydiumLaunchpadPluginRequirements = ClientWithRpc<GetAccountInfoApi & GetMultipleAccountsApi> &
    ClientWithPayer &
    ClientWithTransactionPlanning &
    ClientWithTransactionSending;

export function raydiumLaunchpadProgram() {
    return <T extends RaydiumLaunchpadPluginRequirements>(
        client: T,
    ): Omit<T, 'raydiumLaunchpad'> & { raydiumLaunchpad: RaydiumLaunchpadPlugin } => {
        return extendClient(client, {
            raydiumLaunchpad: <RaydiumLaunchpadPlugin>{
                accounts: {
                    globalConfig: Object.freeze({
                        ...getGlobalConfigCodec(),
                        fetch: (address, config) => fetchGlobalConfig(client.rpc, address, config),
                        fetchAll: (addresses, config) => fetchAllGlobalConfig(client.rpc, addresses, config),
                        fetchAllMaybe: (addresses, config) => fetchAllMaybeGlobalConfig(client.rpc, addresses, config),
                        fetchMaybe: (address, config) => fetchMaybeGlobalConfig(client.rpc, address, config),
                    }),
                    platformConfig: Object.freeze({
                        ...getPlatformConfigCodec(),
                        fetch: (address, config) => fetchPlatformConfig(client.rpc, address, config),
                        fetchAll: (addresses, config) => fetchAllPlatformConfig(client.rpc, addresses, config),
                        fetchAllMaybe: (addresses, config) =>
                            fetchAllMaybePlatformConfig(client.rpc, addresses, config),
                        fetchMaybe: (address, config) => fetchMaybePlatformConfig(client.rpc, address, config),
                    }),
                    poolState: Object.freeze({
                        ...getPoolStateCodec(),
                        fetch: (address, config) => fetchPoolState(client.rpc, address, config),
                        fetchAll: (addresses, config) => fetchAllPoolState(client.rpc, addresses, config),
                        fetchAllMaybe: (addresses, config) => fetchAllMaybePoolState(client.rpc, addresses, config),
                        fetchMaybe: (address, config) => fetchMaybePoolState(client.rpc, address, config),
                    }),
                    vestingRecord: Object.freeze({
                        ...getVestingRecordCodec(),
                        fetch: (address, config) => fetchVestingRecord(client.rpc, address, config),
                        fetchAll: (addresses, config) => fetchAllVestingRecord(client.rpc, addresses, config),
                        fetchAllMaybe: (addresses, config) => fetchAllMaybeVestingRecord(client.rpc, addresses, config),
                        fetchMaybe: (address, config) => fetchMaybeVestingRecord(client.rpc, address, config),
                    }),
                },
                events: {
                    claimVestedEvent: getClaimVestedEventDecoder(),
                    createVestingEvent: getCreateVestingEventDecoder(),
                    poolCreateEvent: getPoolCreateEventDecoder(),
                    tradeEvent: getTradeEventDecoder(),
                },
                instructions: {
                    buyExactIn: input =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getBuyExactInInstructionAsync({ ...input, payer: input.payer ?? client.payer }),
                        ),
                    buyExactOut: input =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getBuyExactOutInstructionAsync({ ...input, payer: input.payer ?? client.payer }),
                        ),
                    claimPlatformFee: input =>
                        addSelfPlanAndSendFunctions(client, getClaimPlatformFeeInstructionAsync(input)),
                    claimVestedToken: input =>
                        addSelfPlanAndSendFunctions(client, getClaimVestedTokenInstructionAsync(input)),
                    collectFee: input => addSelfPlanAndSendFunctions(client, getCollectFeeInstructionAsync(input)),
                    collectMigrateFee: input =>
                        addSelfPlanAndSendFunctions(client, getCollectMigrateFeeInstructionAsync(input)),
                    createConfig: input => addSelfPlanAndSendFunctions(client, getCreateConfigInstructionAsync(input)),
                    createPlatformConfig: input =>
                        addSelfPlanAndSendFunctions(client, getCreatePlatformConfigInstructionAsync(input)),
                    createVestingAccount: input =>
                        addSelfPlanAndSendFunctions(client, getCreateVestingAccountInstructionAsync(input)),
                    initialize: input =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getInitializeInstructionAsync({ ...input, payer: input.payer ?? client.payer }),
                        ),
                    migrateToAmm: input =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getMigrateToAmmInstructionAsync({ ...input, payer: input.payer ?? client.payer }),
                        ),
                    migrateToCpswap: input =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getMigrateToCpswapInstructionAsync({ ...input, payer: input.payer ?? client.payer }),
                        ),
                    sellExactIn: input =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getSellExactInInstructionAsync({ ...input, payer: input.payer ?? client.payer }),
                        ),
                    sellExactOut: input =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getSellExactOutInstructionAsync({ ...input, payer: input.payer ?? client.payer }),
                        ),
                    updateConfig: input => addSelfPlanAndSendFunctions(client, getUpdateConfigInstruction(input)),
                    updatePlatformConfig: input =>
                        addSelfPlanAndSendFunctions(client, getUpdatePlatformConfigInstructionAsync(input)),
                },
                pdas: {
                    authority: findAuthorityPda,
                    eventAuthority: findEventAuthorityPda,
                    vestingRecord: findVestingRecordPda,
                    globalConfig: findGlobalConfigPda,
                    platformConfig: findPlatformConfigPda,
                    poolState: findPoolStatePda,
                    baseVault: findBaseVaultPda,
                    quoteVault: findQuoteVaultPda,
                    ammPool: findAmmPoolPda,
                    ammAuthority: findAmmAuthorityPda,
                    ammOpenOrders: findAmmOpenOrdersPda,
                    ammLpMint: findAmmLpMintPda,
                    ammBaseVault: findAmmBaseVaultPda,
                    ammQuoteVault: findAmmQuoteVaultPda,
                    ammTargetOrders: findAmmTargetOrdersPda,
                    ammConfig: findAmmConfigPda,
                    cpswapAuthority: findCpswapAuthorityPda,
                    cpswapLpMint: findCpswapLpMintPda,
                    cpswapBaseVault: findCpswapBaseVaultPda,
                    cpswapQuoteVault: findCpswapQuoteVaultPda,
                    cpswapObservation: findCpswapObservationPda,
                    lockAuthority: findLockAuthorityPda,
                },
                identifyAccount: identifyAccount,
                identifyInstruction: identifyInstruction,
                parseInstruction: parseInstruction,
            },
        });
    };
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
