/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    containsBytes,
    fixEncoderSize,
    getAddressDecoder,
    getBytesEncoder,
    getStructDecoder,
    getU64Decoder,
    type Address,
    type FixedSizeDecoder,
    type ReadonlyUint8Array,
} from '@solana/kit';
import { RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS } from '../programs/index.js';
import { ANCHOR_EVENT_CPI_DISCRIMINATOR } from './anchorEventCpiDiscriminator.framing.js';

export const CLAIM_VESTED_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
    21, 194, 114, 87, 120, 211, 226, 32,
]);

export function getClaimVestedEventDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(CLAIM_VESTED_EVENT_DISCRIMINATOR);
}

export type ClaimVestedEvent = { poolState: Address; beneficiary: Address; claimAmount: bigint };

let getClaimVestedEventDecoderCache: FixedSizeDecoder<ClaimVestedEvent> | undefined;

export function getClaimVestedEventDecoder(): FixedSizeDecoder<ClaimVestedEvent> {
    return (getClaimVestedEventDecoderCache ??= getStructDecoder([
        ['poolState', getAddressDecoder()],
        ['beneficiary', getAddressDecoder()],
        ['claimAmount', getU64Decoder()],
    ]));
}

/**
 * Checks whether the event data matches the framing and discriminator bytes of a
 * {@link ClaimVestedEvent}, without decoding. Never throws.
 *
 * Returns `false` unless `event.programAddress` is RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS.
 * Raw bytes carry no emitter and SKIP that check.
 *
 * @see parseClaimVestedEvent to decode the matching data
 */
export function isClaimVestedEvent(
    event: { data: ReadonlyUint8Array; programAddress: Address } | ReadonlyUint8Array,
): boolean {
    if ('data' in event && event.programAddress !== RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS) return false;
    const data = 'data' in event ? event.data : event;
    return (
        containsBytes(data, ANCHOR_EVENT_CPI_DISCRIMINATOR, 0) &&
        containsBytes(data, CLAIM_VESTED_EVENT_DISCRIMINATOR, 8)
    );
}

/**
 * Parses raw event data as a {@link ClaimVestedEvent}. Returns `null` on framing or discriminator
 * mismatch; throws if the event matches but its body fails to decode.
 *
 * Returns `null` unless `event.programAddress` is RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS.
 * Raw bytes carry no emitter and SKIP that check.
 *
 * @see isClaimVestedEvent to check without decoding
 * @see identifyEvent to identify any program event
 * @see parseEvent
 */
export function parseClaimVestedEvent(
    event: { data: ReadonlyUint8Array; programAddress: Address } | ReadonlyUint8Array,
): ClaimVestedEvent | null {
    const checkedEvent = 'data' in event ? { data: event.data, programAddress: event.programAddress } : event;
    if (!isClaimVestedEvent(checkedEvent)) {
        return null;
    }
    const data = 'data' in checkedEvent ? checkedEvent.data : checkedEvent;
    return getClaimVestedEventDecoder().decode(
        data,
        ANCHOR_EVENT_CPI_DISCRIMINATOR.length + CLAIM_VESTED_EVENT_DISCRIMINATOR.length,
    );
}
