/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    containsBytes,
    fixEncoderSize,
    getAddressDecoder,
    getBytesEncoder,
    getStructDecoder,
    type Address,
    type Decoder,
    type ReadonlyUint8Array,
} from '@solana/kit';
import {
    getCurveParamsDecoder,
    getMintParamsDecoder,
    getVestingParamsDecoder,
    type CurveParams,
    type MintParams,
    type VestingParams,
} from '../types/index.js';
import { ANCHOR_EVENT_CPI_DISCRIMINATOR } from './anchorEventCpiDiscriminator.framing.js';

export const POOL_CREATE_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
    151, 215, 226, 9, 118, 161, 115, 174,
]);

export function getPoolCreateEventDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(POOL_CREATE_EVENT_DISCRIMINATOR);
}

export type PoolCreateEvent = {
    poolState: Address;
    creator: Address;
    config: Address;
    baseMintParam: MintParams;
    curveParam: CurveParams;
    vestingParam: VestingParams;
};

let getPoolCreateEventDecoderCache: Decoder<PoolCreateEvent> | undefined;

export function getPoolCreateEventDecoder(): Decoder<PoolCreateEvent> {
    return (getPoolCreateEventDecoderCache ??= getStructDecoder([
        ['poolState', getAddressDecoder()],
        ['creator', getAddressDecoder()],
        ['config', getAddressDecoder()],
        ['baseMintParam', getMintParamsDecoder()],
        ['curveParam', getCurveParamsDecoder()],
        ['vestingParam', getVestingParamsDecoder()],
    ]));
}

export function decodePoolCreateEvent(data: ReadonlyUint8Array): PoolCreateEvent {
    if (!containsBytes(data, ANCHOR_EVENT_CPI_DISCRIMINATOR, 0)) {
        throw new Error('Invalid event CPI framing for poolCreateEvent');
    }
    if (!containsBytes(data, POOL_CREATE_EVENT_DISCRIMINATOR, 8)) {
        throw new Error('Invalid event discriminator for poolCreateEvent');
    }
    return getPoolCreateEventDecoder().decode(
        data,
        ANCHOR_EVENT_CPI_DISCRIMINATOR.length + POOL_CREATE_EVENT_DISCRIMINATOR.length,
    );
}
