/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { containsBytes, type ReadonlyUint8Array } from '@solana/kit';
import { ANCHOR_EVENT_CPI_DISCRIMINATOR } from './anchorEventCpiDiscriminator.framing.js';
import {
    CLAIM_VESTED_EVENT_DISCRIMINATOR,
    getClaimVestedEventDecoder,
    type ClaimVestedEvent,
} from './claimVestedEvent.js';
import {
    CREATE_VESTING_EVENT_DISCRIMINATOR,
    getCreateVestingEventDecoder,
    type CreateVestingEvent,
} from './createVestingEvent.js';
import { getPoolCreateEventDecoder, POOL_CREATE_EVENT_DISCRIMINATOR, type PoolCreateEvent } from './poolCreateEvent.js';
import { getTradeEventDecoder, TRADE_EVENT_DISCRIMINATOR, type TradeEvent } from './tradeEvent.js';

/** Event kinds of the raydiumLaunchpad program. */
export type EventType = 'claimVestedEvent' | 'createVestingEvent' | 'poolCreateEvent' | 'tradeEvent';

/**
 * Identifies raydiumLaunchpad event data by its discriminators.
 * Returns `null` when the data matches no known event.
 */
export function identifyEvent(event: { data: ReadonlyUint8Array } | ReadonlyUint8Array): EventType | null {
    const data = 'data' in event ? event.data : event;
    if (
        containsBytes(data, ANCHOR_EVENT_CPI_DISCRIMINATOR, 0) &&
        containsBytes(data, CLAIM_VESTED_EVENT_DISCRIMINATOR, 8)
    ) {
        return 'claimVestedEvent';
    }
    if (
        containsBytes(data, ANCHOR_EVENT_CPI_DISCRIMINATOR, 0) &&
        containsBytes(data, CREATE_VESTING_EVENT_DISCRIMINATOR, 8)
    ) {
        return 'createVestingEvent';
    }
    if (
        containsBytes(data, ANCHOR_EVENT_CPI_DISCRIMINATOR, 0) &&
        containsBytes(data, POOL_CREATE_EVENT_DISCRIMINATOR, 8)
    ) {
        return 'poolCreateEvent';
    }
    if (containsBytes(data, ANCHOR_EVENT_CPI_DISCRIMINATOR, 0) && containsBytes(data, TRADE_EVENT_DISCRIMINATOR, 8)) {
        return 'tradeEvent';
    }
    return null;
}

/** Parsed raydiumLaunchpad event: the event kind tag plus its decoded payload. */
export type ParsedEvent =
    | { kind: 'claimVestedEvent'; payload: ClaimVestedEvent }
    | { kind: 'createVestingEvent'; payload: CreateVestingEvent }
    | { kind: 'poolCreateEvent'; payload: PoolCreateEvent }
    | { kind: 'tradeEvent'; payload: TradeEvent };

/**
 * Parses raydiumLaunchpad event data into its event kind and decoded payload.
 * Returns `null` when no known event matches; throws if a matched event fails to decode.
 */
export function parseEvent(event: { data: ReadonlyUint8Array } | ReadonlyUint8Array): ParsedEvent | null {
    const data = 'data' in event ? event.data : event;
    const eventType = identifyEvent(event);
    if (eventType === null) return null;
    switch (eventType) {
        case 'claimVestedEvent': {
            return {
                kind: 'claimVestedEvent',
                payload: getClaimVestedEventDecoder().decode(
                    data,
                    ANCHOR_EVENT_CPI_DISCRIMINATOR.length + CLAIM_VESTED_EVENT_DISCRIMINATOR.length,
                ),
            };
        }
        case 'createVestingEvent': {
            return {
                kind: 'createVestingEvent',
                payload: getCreateVestingEventDecoder().decode(
                    data,
                    ANCHOR_EVENT_CPI_DISCRIMINATOR.length + CREATE_VESTING_EVENT_DISCRIMINATOR.length,
                ),
            };
        }
        case 'poolCreateEvent': {
            return {
                kind: 'poolCreateEvent',
                payload: getPoolCreateEventDecoder().decode(
                    data,
                    ANCHOR_EVENT_CPI_DISCRIMINATOR.length + POOL_CREATE_EVENT_DISCRIMINATOR.length,
                ),
            };
        }
        case 'tradeEvent': {
            return {
                kind: 'tradeEvent',
                payload: getTradeEventDecoder().decode(
                    data,
                    ANCHOR_EVENT_CPI_DISCRIMINATOR.length + TRADE_EVENT_DISCRIMINATOR.length,
                ),
            };
        }
    }
}
