/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { type Address, type ProgramDerivedAddress, type ProgramDerivedAddressBump } from '@solana/kit';

export const AMM_AUTHORITY_PDA_ADDRESS =
    '5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1' as Address<'5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'>;

export function findAmmAuthorityPda(): ProgramDerivedAddress {
    return [AMM_AUTHORITY_PDA_ADDRESS, 254 as ProgramDerivedAddressBump];
}
