/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    address,
    getAddressEncoder,
    getBytesEncoder,
    getProgramDerivedAddress,
    type Address,
    type ProgramDerivedAddress,
} from '@solana/kit';

export type AmmBaseVaultSeeds = {
    market: Address;
};

export async function findAmmBaseVaultPda(seeds: AmmBaseVaultSeeds): Promise<ProgramDerivedAddress> {
    return await getProgramDerivedAddress({
        programAddress:
            '675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8' as Address<'675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8'>,
        seeds: [
            getAddressEncoder().encode(address('675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8')),
            getAddressEncoder().encode(seeds.market),
            getBytesEncoder().encode(
                new Uint8Array([
                    99, 111, 105, 110, 95, 118, 97, 117, 108, 116, 95, 97, 115, 115, 111, 99, 105, 97, 116, 101, 100,
                    95, 115, 101, 101, 100,
                ]),
            ),
        ],
    });
}
