/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { getBytesEncoder, getProgramDerivedAddress, type Address, type ProgramDerivedAddress } from '@solana/kit';

export async function findAmmConfigPda(
    config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
    const {
        programAddress = '675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8' as Address<'675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8'>,
    } = config;
    return await getProgramDerivedAddress({
        programAddress,
        seeds: [
            getBytesEncoder().encode(
                new Uint8Array([
                    97, 109, 109, 95, 99, 111, 110, 102, 105, 103, 95, 97, 99, 99, 111, 117, 110, 116, 95, 115, 101,
                    101, 100,
                ]),
            ),
        ],
    });
}
