/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { type Address, type ProgramDerivedAddress, type ProgramDerivedAddressBump } from '@solana/kit';

export const AMM_CONFIG_PDA_ADDRESS =
    '9DCxsMizn3H1hprZ7xWe6LDzeUeZBksYFpBWBtSf1PQX' as Address<'9DCxsMizn3H1hprZ7xWe6LDzeUeZBksYFpBWBtSf1PQX'>;

export function findAmmConfigPda(): ProgramDerivedAddress {
    return [AMM_CONFIG_PDA_ADDRESS, 255 as ProgramDerivedAddressBump];
}
