/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    getAddressEncoder,
    getBytesEncoder,
    getProgramDerivedAddress,
    type Address,
    type ProgramDerivedAddress,
} from '@solana/kit';

export type CpswapObservationSeeds = {
    cpswapPool: Address;
};

export async function findCpswapObservationPda(seeds: CpswapObservationSeeds): Promise<ProgramDerivedAddress> {
    return await getProgramDerivedAddress({
        programAddress:
            'CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C' as Address<'CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C'>,
        seeds: [
            getBytesEncoder().encode(new Uint8Array([111, 98, 115, 101, 114, 118, 97, 116, 105, 111, 110])),
            getAddressEncoder().encode(seeds.cpswapPool),
        ],
    });
}
