/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    getAddressEncoder,
    getBytesEncoder,
    getProgramDerivedAddress,
    type Address,
    type ProgramDerivedAddress,
} from '@solana/kit';

export type CpswapBaseVaultSeeds = {
    cpswapPool: Address;
    baseMint: Address;
};

export async function findCpswapBaseVaultPda(seeds: CpswapBaseVaultSeeds): Promise<ProgramDerivedAddress> {
    return await getProgramDerivedAddress({
        programAddress:
            'CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C' as Address<'CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C'>,
        seeds: [
            getBytesEncoder().encode(new Uint8Array([112, 111, 111, 108, 95, 118, 97, 117, 108, 116])),
            getAddressEncoder().encode(seeds.cpswapPool),
            getAddressEncoder().encode(seeds.baseMint),
        ],
    });
}
