/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { type Address, type ProgramDerivedAddress, type ProgramDerivedAddressBump } from '@solana/kit';

export const EVENT_AUTHORITY_PDA_ADDRESS =
    '2DPAtwB8L12vrMRExbLuyGnC7n2J5LNoZQSejeQGpwkr' as Address<'2DPAtwB8L12vrMRExbLuyGnC7n2J5LNoZQSejeQGpwkr'>;

export function findEventAuthorityPda(): ProgramDerivedAddress {
    return [EVENT_AUTHORITY_PDA_ADDRESS, 255 as ProgramDerivedAddressBump];
}
