/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { getBytesEncoder, getProgramDerivedAddress, type ProgramDerivedAddress } from '@solana/kit';
import { RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS } from '../programs/index.js';

export async function findEventAuthorityPda(): Promise<ProgramDerivedAddress> {
    return await getProgramDerivedAddress({
        programAddress: RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
        seeds: [
            getBytesEncoder().encode(
                new Uint8Array([95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121]),
            ),
        ],
    });
}
