/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    getAddressEncoder,
    getBytesEncoder,
    getProgramDerivedAddress,
    getU16Encoder,
    getU8Encoder,
    type Address,
    type ProgramDerivedAddress,
} from '@solana/kit';
import { RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS } from '../programs/index.js';

export type GlobalConfigSeeds = {
    quoteTokenMint: Address;
    curveType: number;
    index: number;
};

export async function findGlobalConfigPda(seeds: GlobalConfigSeeds): Promise<ProgramDerivedAddress> {
    return await getProgramDerivedAddress({
        programAddress: RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
        seeds: [
            getBytesEncoder().encode(new Uint8Array([103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103])),
            getAddressEncoder().encode(seeds.quoteTokenMint),
            getU8Encoder().encode(seeds.curveType),
            getU16Encoder().encode(seeds.index),
        ],
    });
}
