/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { type Address, type ProgramDerivedAddress, type ProgramDerivedAddressBump } from '@solana/kit';

export const LOCK_AUTHORITY_PDA_ADDRESS =
    '3f7GcQFG397GAaEnv51zR6tsTVihYRydnydDD1cXekxH' as Address<'3f7GcQFG397GAaEnv51zR6tsTVihYRydnydDD1cXekxH'>;

export function findLockAuthorityPda(): ProgramDerivedAddress {
    return [LOCK_AUTHORITY_PDA_ADDRESS, 255 as ProgramDerivedAddressBump];
}
