/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    getAddressEncoder,
    getBytesEncoder,
    getProgramDerivedAddress,
    type Address,
    type ProgramDerivedAddress,
} from '@solana/kit';

export type PlatformConfigSeeds = {
    platformAdmin: Address;
};

export async function findPlatformConfigPda(
    seeds: PlatformConfigSeeds,
    config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
    const {
        programAddress = 'LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj' as Address<'LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj'>,
    } = config;
    return await getProgramDerivedAddress({
        programAddress,
        seeds: [
            getBytesEncoder().encode(
                new Uint8Array([112, 108, 97, 116, 102, 111, 114, 109, 95, 99, 111, 110, 102, 105, 103]),
            ),
            getAddressEncoder().encode(seeds.platformAdmin),
        ],
    });
}
