/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    getAddressEncoder,
    getBytesEncoder,
    getProgramDerivedAddress,
    type Address,
    type ProgramDerivedAddress,
} from '@solana/kit';
import { RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS } from '../programs/index.js';

export type PlatformConfigSeeds = {
    platformAdmin: Address;
};

export async function findPlatformConfigPda(seeds: PlatformConfigSeeds): Promise<ProgramDerivedAddress> {
    return await getProgramDerivedAddress({
        programAddress: RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
        seeds: [
            getBytesEncoder().encode(
                new Uint8Array([112, 108, 97, 116, 102, 111, 114, 109, 95, 99, 111, 110, 102, 105, 103]),
            ),
            getAddressEncoder().encode(seeds.platformAdmin),
        ],
    });
}
