/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    getAddressEncoder,
    getBytesEncoder,
    getProgramDerivedAddress,
    type Address,
    type ProgramDerivedAddress,
} from '@solana/kit';
import { RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS } from '../programs/index.js';

export type VestingRecordSeeds = {
    poolState: Address;
    beneficiary: Address;
};

export async function findVestingRecordPda(seeds: VestingRecordSeeds): Promise<ProgramDerivedAddress> {
    return await getProgramDerivedAddress({
        programAddress: RAYDIUM_LAUNCHPAD_PROGRAM_ADDRESS,
        seeds: [
            getBytesEncoder().encode(new Uint8Array([112, 111, 111, 108, 95, 118, 101, 115, 116, 105, 110, 103])),
            getAddressEncoder().encode(seeds.poolState),
            getAddressEncoder().encode(seeds.beneficiary),
        ],
    });
}
